# Generated by Django 4.1.7 on 2023-04-24 15:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=10)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=100000)),
                ('mobile', models.CharField(default='', max_length=13, null=True)),
                ('address_1', models.CharField(default='', max_length=50, null=True)),
                ('address_2', models.CharField(default='', max_length=50, null=True)),
                ('post_code', models.CharField(default='', max_length=7, null=True)),
                ('state', models.CharField(default='', max_length=50, null=True)),
                ('area', models.CharField(default='', max_length=50, null=True)),
                ('country', models.CharField(default='', max_length=50, null=True)),
                ('region', models.CharField(default='', max_length=50, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
